Provide private API to set CPPInstance `__reduce__` callback
This API addressed the following problem im ROOT:

The CPPIntance type is immutable, and new attributes can't be set:
```txt
import cppyy
>>> setattr(cppyy._backend.CPPInstance, "test", 10)
Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    setattr(cppyy._backend.CPPInstance, "test", 10)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot set 'test' attribute of immutable type 'cppyy.CPPInstance'
>>>
```

In our pythonizations, we still want to monkey-patch a `__reduce__`
method anyway, and to make Python not complain we to a hack by setting
the attribute with the C Python API using `PyObject_GenericSetAttr`.
This function doesn't normally do any safety checks, and our monkey
patching works.

However, the Python debug build is not having any of that, thanks to a
new assert that was added a year ago:

https://github.com/python/cpython/blame/c419af9e277bea7dd78f4defefc752fe93b0b8ec/Objects/object.c#L1921

To make the ROOT Python interface work with debug builds of the Python
interpreter, we therefore have to implement adding the reduce method
properly.

This commit suggests to achieve this by defining the `__reduce__` method
in the immutable CPPInstance type within CPyCppyy, but in such a way
that its implementation can be routed to ROOT via a private API.